SyntaxError: Identifier 'VAL_COLOR_1' has already been declared
import {VAL_COLOR_1} from "./embed.js"
import fs from "fs";
import {VAL_COLOR_1} from "./embed.js";